### ISSUE TITLE
Import other zwave devices?

### ISSUE THREAD

**Issue by chrisbsmith** [jasperpatterson/homebridge-abode-locks#1]
Have you thought about importing other zwave devices connected to an Abode gateway?  I stumbled on your plugin, but I don't manage my locks through Abode.  I have several zwave light switches and outlets that I installed pre-homekit era that I'd like to include though homebridge vice home-assistant. 

It seems like like you're already looping over all of the devices from Abode here and would image this is where other device types could be set.

https://github.com/jasperpatterson/homebridge-abode-locks/blob/4cc074e2cd6dce00827907e45df426e2eda192be/src/platform.ts#L89

I'm new to TypeScript but am willing to try though it'll take me some time and I'd have to reference your code a ton.  

Anyways, just thought I'd ask to see if you'd thought about this.  Thanks for contributing to the community.

**Comment by jasperpatterson** [comment]
Personally I only have door locks, so that's where my interest was, and all I had the ability to test.

Assuming the other Zwave devices work in a similar way, my code shouldn't be too difficult to reuse for them. You'd need to write the corresponding Homebridge accessories, and some abode API calls for controlling the device (similar to `controlLock`).

**Comment by chrisbsmith** [comment]
I get it. Your code is a great jumping off point

Admittedly, I am not much of a developer anymore. I frequent in bash and YAML more than I do anything else

I've been playing with the API a bit today in Postman but can't figure how to update the status through a PUT command. I've tried passing `?status=On` as a parameter and I've tried as a body request. Do you have any tips or pointers?  I grabbed my bearer token from the dev tools in chrome when logging in. This lets me at least query the decides so I figured I could set too. 

Thanks!

**Comment by jasperpatterson** [comment]
PUT would generally use the request body. I'd recommend controlling the device on abode's website while using the network inspector in Chrome, then you can make sure you're matching the same URL, body, and headers as they do.

**Comment by chrisbsmith** [comment]
Thanks for the pointers.  I must be missing something to use Postman, but I've been able to make some really great progress on a plugin to integrate lights and switches.  Your code has been the only reason I've been able to get anything done!
